### ISSUE TITLE
No module named 'ocvl_addon' on Blender 2.92

### ISSUE THREAD

**Issue by urajcic** [feler404/ocvl-addon#44]
Traceback (most recent call last):
  File "D:\blender\2.92\2.92\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\VPS\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\ocvl-addon-master\__init__.py", line 49, in register
    from ocvl_addon import logger_conf
ModuleNotFoundError: No module named 'ocvl_addon'

**Comment by Hoodgail** [comment]
me too

**Comment by AleksVidmantas** [comment]
Rename ocvl-addon-master to ocvl_addon and rezip. Close Blender and try reinstalling.
